// generated by gemini 3.1 pro
export const stripImageMetadata = (file: File): Promise<File> => {
  return new Promise((resolve, reject) => {
    // Only process images. Pass through videos or other files unmodified.
    if (!file.type.startsWith("image/")) {
      return resolve(file);
    }

    const img = new Image();
    const objectUrl = URL.createObjectURL(file);

    img.onload = () => {
      URL.revokeObjectURL(objectUrl); // Clean up memory

      // Create an invisible canvas matching the image dimensions
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;

      const ctx = canvas.getContext("2d");
      if (!ctx) {
        return reject(new Error("Failed to get canvas context"));
      }

      // Draw the image. This leaves the EXIF data behind.
      ctx.drawImage(img, 0, 0);

      // Export the clean image.
      // Defaulting to jpeg at 90% quality to match standard web practices.
      const mimeType = file.type === "image/png" ? "image/png" : "image/jpeg";
      const quality = mimeType === "image/jpeg" ? 0.9 : undefined;

      canvas.toBlob(
        (blob) => {
          if (!blob) {
            return reject(new Error("Canvas to Blob conversion failed"));
          }

          // Re-package the clean Blob back into a File object.
          // Note: Generating a new Date.now() wipes the original file's creation timestamp.
          const cleanFile = new File([blob], file.name, {
            type: mimeType,
            lastModified: Date.now(),
          });

          resolve(cleanFile);
        },
        mimeType,
        quality
      );
    };

    img.onerror = () => {
      URL.revokeObjectURL(objectUrl);
      reject(new Error("Failed to load image for processing"));
    };

    img.src = objectUrl;
  });
};
